swagger: "2.0"
info:
  title: API SendSMS v1 BRANDON
  description: |
    API para envio de mensajes de texto, se debe de generar un token de acceso para el consumo del metodo

    Servicio OAuth2:
    - [API OAuth2](https://dev-portal-qa.claro.com.gt/apis/oauthv2)
  version: "1.0.0"

host: api-qa-cloud.cenam.claro.com.gt
schemes:
  - https
basePath: /

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
  apiKey:
    type: apiKey
    name: Authorization
    in: header

security:
  - bearerAuth: []
  - apiKey: []

paths:
  /sendsmsBRANDON/v1/SendSms:
    post:
      summary: SendSMS
      operationId: sendSMS
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/requestToSend'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/responseSend'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/responseError'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/responseError'
        429:
          description: Too Many Requests
          schema:
            $ref: '#/definitions/responseError'
        default:
          description: Error
          schema:
            $ref: '#/definitions/responseError'

definitions:
  requestToSend:
    type: object
    required: [App, Source, Msisdn, Message]
    properties:
      App:
        type: string
        example: API
        maxLength: 5
        pattern: ^[A-Z0-9]+$
      Source:
        type: string
        example: Claro
        maxLength: 10
        pattern: ^[A-Za-z0-9]+$
      Msisdn:
        type: string
        example: 50211223344
        maxLength: 11
        pattern: ^[0-9]+$
      Message:
        type: string
        example: Mensaje de prueba de SMS desde API SendSMS
        maxLength: 150
  responseSend:
    type: object
    required: [description, responseMessage]
    properties:
      description:
        type: string
        example: S
        maxLength: 1
        pattern: ^[S|E]$
      responseMessage:
        type: string
        example: mensaje enviado
  responseError:
    type: object
    required: [status, message]
    properties:
      status:
        type: integer
        example: 400
      message:
        type: string
        example: Bad Request
